<?php
if (isset($_POST['submit'])) {

    $firstName = trim($_POST["firstName"]);
    $lastName = trim($_POST["lastName"]);
    $email = trim($_POST["email"]);
    $phone = trim($_POST["phone"]);
    $dob = trim($_POST["dob"]);
    $guest_password = $_POST["password"];
    $confirmPassword = $_POST["confirmPassword"];





    // Redirect to sign up page
    function redirectBack()
    {
        header('Location: ../../View/Authentication/SignUp/signup.html');
        exit();
    }

    // Check for empty fields
    if (
        $firstName === '' || $lastName === '' || $email === '' ||
        $phone === '' || $dob === '' || $password === '' || $confirmPassword === ''
    ) {
        redirectBack();
    }

    // Email validation
    if (strpos($email, '@') === false) {
        redirectBack();
    }

    $emailParts = explode('@', $email, 2);
    if (count($emailParts) !== 2) {
        redirectBack();
    }

    list($localPart, $domain) = $emailParts;

    if ($domain !== 'gmail.com') {
        redirectBack();
    }

    if ($localPart !== strtolower($localPart)) {
        redirectBack();
    }

    $firstChar = $localPart[0] ?? '';
    if ($firstChar >= '0' && $firstChar <= '9') {
        redirectBack();
    }

    if (strpos($localPart, ' ') !== false) {
        redirectBack();
    }

    // Password validation
    function isValidPassword($password)
    {
        if (strlen($password) < 8) return false;

        $hasUpper = false;
        $hasLower = false;
        $hasSpecial = false;
        $hasNumber = false;

        $specialChars = "!@#$";

        for ($i = 0; $i < strlen($password); $i++) {
            $char = $password[$i];

            if ($char >= 'A' && $char <= 'Z') $hasUpper = true;
            else if ($char >= 'a' && $char <= 'z') $hasLower = true;
            else if (strpos($specialChars, $char) !== false) $hasSpecial = true;
            else if ($char >= '0' && $char <= '9') $hasNumber = true;

            if ($hasUpper && $hasLower && $hasSpecial && $hasNumber) {
                return true;
            }
        }

        return false;
    }

    if (!isValidPassword($guest_password)) {
        redirectBack();
    }

    // Confirm password check
    if ($guest_password !== $confirmPassword) {
        redirectBack();
    }

    // Phone validation
    if (strlen($phone) !== 11) {
        redirectBack();
    }

    if ($phone[0] !== '0' || $phone[1] !== '1') {
        redirectBack();
    }


    $role = "guest";

    $location = "127.0.0.1";
    $userName = "root";
    $password = "";
    $dbName = "hotel-reservation";
    $connection = mysqli_connect($location, $userName, $password, $dbName);

    //auto generated id
    function getAutoGeneratedId($connection)
    {
        $query = "SELECT user_id FROM users ORDER BY id DESC LIMIT 1";
        $result = mysqli_query($connection, $query);
        $row = mysqli_fetch_assoc($result);
        if ($row) {
            $last_request_id = $row['user_id'];
            // Explode and increment
            $new_request_id = "g-" . ((int)explode('-', $last_request_id)[1] + 1);
        }
        return $new_request_id;
    }

    //checking for duplicate  email address
    function IsEmailAddressAlreadyExists($connection, $emailAddress)
    {
        $query = "SELECT email FROM `users`";
        $result = mysqli_query($connection, $query);
        while ($row = mysqli_fetch_assoc($result)) {
            // print_r($row);
            // $em = $row['email'];
            // print_r($em);
            if ($row['email'] == $emailAddress) {
                echo "Email address already exists";
                return false;
            }
        }
        return true;
    }

    
    if (IsEmailAddressAlreadyExists($connection, $email)) {
        echo "can added";
        $user_id = getAutoGeneratedId($connection);

        $query = "INSERT INTO `users` 
        (`id`,`user_id`, `email`, `phone`, `first_name`, `last_name`, `dob`, `role`, `password`) 
        VALUES (null,'$user_id', '$email', '$phone', '$firstName', '$lastName', '$dob', '$role', '$guest_password')";


        $result = mysqli_query($connection, $query);

        if ($result) {
            // Set success cookie and redirect
            session_start();
            $_SESSION['status'] = true;
            $_SESSION['guest-id'] = $user_id;
            setcookie('status', 'true', time() + 5000, '/');
            header('Location: ./afterSignUp.php');
            exit();
        } else {
            echo "Unsuccessful";
        }
    }
    else{
        echo "Invalid";
        return;
    }
} else {
    header("Location: ../../View/Authentication/SignUp/signup.html");
    exit;
}
